module4-task1
htmlacademy-javascript/832991-keksobooking-22 pull request #4
Opened 2021-02-24 13:09 UTC by foontomas

Разбил код на модули, добавил строку для работы с модулями в package.json

2021-02-25 07:03 UTC, Dima-Dim requested changes
Для неизменяемых переменных использовать const.
Проверить нейминг массивов и функций.
Избавиться от магических цифр.

2021-02-25 07:03 UTC, Dima-Dim commented on js/util.js
> +const intRangeReturn = (firstNumber, secondNumber) => {
Практически каждая функция что-то `return` :) такое общее слово не сильно добавляет понимания того что же там происходит и для чего эта функция. Глагол ради глагола, а не для смысла.

2021-02-26 10:36 UTC, foontomas commented on js/util.js
> +const intRangeReturn = (firstNumber, secondNumber) => {
Заменил return на randomize

2021-02-26 10:36 UTC, foontomas commented on js/data.js
> +      avatar: 'img/avatars/user0' + intRangeReturn(1, 8) + '.png',
Заменил шаблонными строками

2021-02-26 10:36 UTC, foontomas commented on js/data.js
> +  const rangeFromX = 35.65000;
Согласно тексту задания для module3-task1: x, число с плавающей точкой — широта, случайное значение от 35.65000 до 35.70000, y, число с плавающей точкой — долгота, случайное значение от 139.70000 до 139.80000, что и отражено в переменных. Переменные вынес наверх, оставил комментарии в коде.

2021-02-27 07:43 UTC, Dima-Dim commented on js/data.js
> +  const rangeFromX = 35.65000;
Вот не переменные, раз по заданию, а константы которые в коде не меняются, значит https://up.htmlacademy.ru/javascript/22/criteries#b7

2021-02-27 07:43 UTC, Dima-Dim commented on js/data.js
> +  const rangeFromX = 35.65000;
Вот не переменные, раз по заданию, а константы которые в коде не меняются, значит https://up.htmlacademy.ru/javascript/22/criteries#b7

2021-02-27 07:46 UTC, Dima-Dim reviewed
Хорошо. Остальное в следующем задании можешь поправить.

2021-02-27 07:46 UTC, Dima-Dim commented on js/data.js
> +const titlesArray = ['cozy home', 'lovely place', 'apartments with picturesque view', 'townhouse in the garden', 'bungalow on the seaside'];
Уже лучше, но в идеале обходится без Array.

2021-02-27 07:46 UTC, Dima-Dim commented on js/data.js
> +const offerTypes = ['palace', 'flat', 'house', 'bungalow'];
Вот как-то так ;)

2021-02-27 07:46 UTC, Dima-Dim commented on js/data.js
> +const rangeFromX = 35.65000; //x, число с плавающей точкой — широта, для диапазона случайных значений от 35.65000
https://up.htmlacademy.ru/javascript/22/criteries#b7

2021-02-27 07:46 UTC, merged